"""Code templates the offline LocalAgent picks from.

Each entry maps a (topic, extension) pair to a string of working code.
Templates are kept short, runnable, and self-contained — the agent
verifies many of them with a follow-up ``run_python`` call.

Topics are detected from the prompt by ``detect_topic`` which scans for
keywords in both English and Russian. If no topic matches, the generic
fallback is used.
"""

from __future__ import annotations

import re

# ── topic keyword patterns ────────────────────────────────────────────

_TOPIC_PATTERNS: dict[str, list[str]] = {
    "fibonacci":      ["fibonacci", "фибоначч", "fib up to"],
    "prime":          ["prime number", "простые числа", "primes up to"],
    "bubble_sort":    ["bubble sort", "сортировка пузырьком", "bubblesort"],
    "quick_sort":     ["quick sort", "quicksort", "быстрая сортировка"],
    "calculator":     ["calculator", "калькулят", "calc.py"],
    "fastapi":        ["fastapi", "rest api", "api server", "rest endpoint"],
    "flask":          ["flask app", "flask api"],
    "guess_number":   ["guess", "угадай число", "guess the number"],
    "password_gen":   ["password generator", "генератор паролей", "random password"],
    "tic_tac_toe":    ["tic tac toe", "крестики нолики"],
    "csv_reader":     ["read csv", "csv reader", "csv file", "чтение csv"],
    "json_pretty":    ["pretty json", "format json", "красив json"],
    "argparse_cli":   ["argparse", "command line tool", "cli script", "cli утилит"],
    "todo_list":      ["todo list", "список дел", "todo app"],
    "html_page":      ["html page", "web page", "html страниц", "landing page"],
    "html_form":      ["html form", "форма", "contact form"],
    "snake_game":     ["snake game", "змейка"],
    "rock_paper":     ["rock paper", "rock-paper-scissors", "камень ножницы"],
    "stopwatch":      ["stopwatch", "секундомер", "timer"],
    "factorial":      ["factorial", "факториал"],
    "palindrome":     ["palindrome", "палиндром"],
    "anagram":        ["anagram", "анаграмм"],
    "word_counter":   ["word counter", "count words", "счётчик слов"],
    "fizzbuzz":       ["fizzbuzz", "fizz buzz"],
    "hello":          ["hello world", "hello", "привет"],
}


def detect_topic(prompt: str) -> str | None:
    """Return the topic key whose pattern best matches ``prompt``."""
    low = prompt.lower()
    for topic, patterns in _TOPIC_PATTERNS.items():
        for pat in patterns:
            if pat in low:
                return topic
    return None


# ── templates: (topic, ext) → content ─────────────────────────────────


def render(topic: str | None, ext: str, prompt_excerpt: str) -> str:
    """Return the template body for ``topic`` + ``ext``, with a sensible fallback."""
    key = (topic or "", ext.lower())
    if key in _TEMPLATES:
        return _TEMPLATES[key]
    # ext-only fallback (the agent at least produces a syntactically valid file).
    if ("", ext.lower()) in _TEMPLATES:
        return _TEMPLATES[("", ext.lower())].replace("{{PROMPT}}", prompt_excerpt[:80])
    # Last-resort generic.
    return f"# Auto-generated by LocalAgent\n# Prompt: {prompt_excerpt[:80]}\n"


# Each template is plain Python (or HTML/etc.) — short, runnable, no deps
# beyond the stdlib. Multi-line strings are kept readable: an extra line
# at the end keeps a trailing newline.

_TEMPLATES: dict[tuple[str, str], str] = {

    # ── Hello world ──────────────────────────────────────────────────
    ("hello", "py"): (
        '"""Hello-world script."""\n\n'
        'def main() -> None:\n'
        '    print("Hello, world!")\n\n\n'
        'if __name__ == "__main__":\n'
        '    main()\n'
    ),
    ("hello", "html"): (
        "<!doctype html>\n<html><head><meta charset='utf-8'><title>Hello</title></head>\n"
        "<body><h1>Hello, world!</h1></body></html>\n"
    ),
    ("hello", "txt"): "Hello, world!\n",
    ("hello", "md"): "# Hello, world!\n",

    # ── Fibonacci ────────────────────────────────────────────────────
    ("fibonacci", "py"): (
        '"""Fibonacci numbers up to a limit."""\n\n'
        'def fib_up_to(limit: int) -> list[int]:\n'
        '    out: list[int] = []\n'
        '    a, b = 0, 1\n'
        '    while a <= limit:\n'
        '        out.append(a)\n'
        '        a, b = b, a + b\n'
        '    return out\n\n\n'
        'if __name__ == "__main__":\n'
        '    print(fib_up_to(100))\n'
    ),

    # ── Prime numbers ────────────────────────────────────────────────
    ("prime", "py"): (
        '"""Prime numbers up to a limit (Sieve of Eratosthenes)."""\n\n'
        'def primes_up_to(n: int) -> list[int]:\n'
        '    if n < 2:\n'
        '        return []\n'
        '    sieve = [True] * (n + 1)\n'
        '    sieve[0] = sieve[1] = False\n'
        '    for i in range(2, int(n**0.5) + 1):\n'
        '        if sieve[i]:\n'
        '            for j in range(i*i, n + 1, i):\n'
        '                sieve[j] = False\n'
        '    return [i for i, p in enumerate(sieve) if p]\n\n\n'
        'if __name__ == "__main__":\n'
        '    print(primes_up_to(50))\n'
    ),

    # ── Sorting ──────────────────────────────────────────────────────
    ("bubble_sort", "py"): (
        '"""Bubble sort, classroom edition."""\n\n'
        'def bubble_sort(items: list[int]) -> list[int]:\n'
        '    a = list(items)\n'
        '    n = len(a)\n'
        '    for i in range(n):\n'
        '        for j in range(0, n - i - 1):\n'
        '            if a[j] > a[j + 1]:\n'
        '                a[j], a[j + 1] = a[j + 1], a[j]\n'
        '    return a\n\n\n'
        'if __name__ == "__main__":\n'
        '    print(bubble_sort([5, 2, 9, 1, 7, 3]))\n'
    ),
    ("quick_sort", "py"): (
        '"""Quick sort with a Lomuto partition."""\n\n'
        'def quick_sort(items: list[int]) -> list[int]:\n'
        '    if len(items) <= 1:\n'
        '        return list(items)\n'
        '    pivot = items[len(items) // 2]\n'
        '    left  = [x for x in items if x < pivot]\n'
        '    mid   = [x for x in items if x == pivot]\n'
        '    right = [x for x in items if x > pivot]\n'
        '    return quick_sort(left) + mid + quick_sort(right)\n\n\n'
        'if __name__ == "__main__":\n'
        '    print(quick_sort([5, 2, 9, 1, 7, 3]))\n'
    ),

    # ── Calculator ───────────────────────────────────────────────────
    ("calculator", "py"): (
        '"""Tiny calculator that parses \\"a OP b\\" expressions."""\n\n'
        'import operator\n\n'
        'OPS = {"+": operator.add, "-": operator.sub, "*": operator.mul, "/": operator.truediv}\n\n\n'
        'def calc(expr: str) -> float:\n'
        '    a, op, b = expr.split()\n'
        '    return OPS[op](float(a), float(b))\n\n\n'
        'if __name__ == "__main__":\n'
        '    print(calc("12 + 5"))\n'
        '    print(calc("8 * 7"))\n'
    ),

    # ── FastAPI ──────────────────────────────────────────────────────
    ("fastapi", "py"): (
        '"""Tiny FastAPI service.\n\n'
        'Run: uvicorn main:app --reload --port 8080\n'
        '"""\n\n'
        'from fastapi import FastAPI\n\n'
        'app = FastAPI(title="Generated API")\n\n'
        '_items: dict[int, str] = {}\n\n\n'
        '@app.get("/items")\n'
        'def list_items():\n'
        '    return _items\n\n\n'
        '@app.post("/items")\n'
        'def add_item(item: dict):\n'
        '    new_id = (max(_items) + 1) if _items else 1\n'
        '    _items[new_id] = item.get("name", "")\n'
        '    return {"id": new_id, "name": _items[new_id]}\n\n\n'
        '@app.delete("/items/{item_id}")\n'
        'def delete_item(item_id: int):\n'
        '    return {"deleted": _items.pop(item_id, None)}\n'
    ),

    # ── Flask ────────────────────────────────────────────────────────
    ("flask", "py"): (
        '"""Tiny Flask app.\n\n'
        'Run: python app.py\n'
        '"""\n\n'
        'from flask import Flask, jsonify\n\n'
        'app = Flask(__name__)\n\n\n'
        '@app.get("/")\n'
        'def index():\n'
        '    return jsonify(message="hello")\n\n\n'
        '@app.get("/ping")\n'
        'def ping():\n'
        '    return jsonify(pong=True)\n\n\n'
        'if __name__ == "__main__":\n'
        '    app.run(port=5000, debug=True)\n'
    ),

    # ── Guess number game ────────────────────────────────────────────
    ("guess_number", "py"): (
        '"""Number-guessing console game."""\n\n'
        'import random\n\n\n'
        'def play(low: int = 1, high: int = 100) -> None:\n'
        '    secret = random.randint(low, high)\n'
        '    tries = 0\n'
        '    while True:\n'
        '        try:\n'
        '            guess = int(input(f"Guess between {low} and {high}: "))\n'
        '        except ValueError:\n'
        '            print("Enter an integer.")\n'
        '            continue\n'
        '        tries += 1\n'
        '        if guess < secret:\n'
        '            print("Higher!")\n'
        '        elif guess > secret:\n'
        '            print("Lower!")\n'
        '        else:\n'
        '            print(f"Got it in {tries} tries!")\n'
        '            return\n\n\n'
        'if __name__ == "__main__":\n'
        '    play()\n'
    ),

    # ── Password generator ───────────────────────────────────────────
    ("password_gen", "py"): (
        '"""Random password generator."""\n\n'
        'import random\n'
        'import string\n\n\n'
        'def make_password(length: int = 16, *, symbols: bool = True) -> str:\n'
        '    alphabet = string.ascii_letters + string.digits\n'
        '    if symbols:\n'
        '        alphabet += "!@#$%^&*-_=+"\n'
        '    return "".join(random.choice(alphabet) for _ in range(length))\n\n\n'
        'if __name__ == "__main__":\n'
        '    for _ in range(3):\n'
        '        print(make_password(20))\n'
    ),

    # ── Tic-tac-toe ──────────────────────────────────────────────────
    ("tic_tac_toe", "py"): (
        '"""Tic-tac-toe core (no UI; verify the win-detection logic)."""\n\n'
        'def winner(board: list[str]) -> str | None:\n'
        '    lines = [\n'
        '        [0,1,2], [3,4,5], [6,7,8],   # rows\n'
        '        [0,3,6], [1,4,7], [2,5,8],   # cols\n'
        '        [0,4,8], [2,4,6],            # diagonals\n'
        '    ]\n'
        '    for a, b, c in lines:\n'
        '        if board[a] != " " and board[a] == board[b] == board[c]:\n'
        '            return board[a]\n'
        '    return None\n\n\n'
        'if __name__ == "__main__":\n'
        '    b = ["X","O","X"," ","X","O","X","O","X"]\n'
        '    print("winner:", winner(b))\n'
    ),

    # ── CSV reader ───────────────────────────────────────────────────
    ("csv_reader", "py"): (
        '"""Read a CSV file and print summary stats per numeric column."""\n\n'
        'import csv\n'
        'import sys\n'
        'from statistics import mean, stdev\n\n\n'
        'def summarize(path: str) -> None:\n'
        '    with open(path, newline="", encoding="utf-8") as f:\n'
        '        reader = csv.DictReader(f)\n'
        '        rows = list(reader)\n'
        '    if not rows:\n'
        '        print("(empty)")\n'
        '        return\n'
        '    print(f"{len(rows)} rows")\n'
        '    for col in rows[0]:\n'
        '        vals = []\n'
        '        for r in rows:\n'
        '            try:\n'
        '                vals.append(float(r[col]))\n'
        '            except (ValueError, TypeError):\n'
        '                pass\n'
        '        if vals:\n'
        '            print(f"  {col}: mean={mean(vals):.2f}, stdev={stdev(vals) if len(vals)>1 else 0:.2f}")\n\n\n'
        'if __name__ == "__main__":\n'
        '    summarize(sys.argv[1] if len(sys.argv) > 1 else "data.csv")\n'
    ),

    # ── JSON pretty-print ────────────────────────────────────────────
    ("json_pretty", "py"): (
        '"""Pretty-print a JSON file."""\n\n'
        'import json\n'
        'import sys\n\n\n'
        'def pretty(path: str) -> None:\n'
        '    with open(path, encoding="utf-8") as f:\n'
        '        data = json.load(f)\n'
        '    print(json.dumps(data, indent=2, ensure_ascii=False, sort_keys=True))\n\n\n'
        'if __name__ == "__main__":\n'
        '    pretty(sys.argv[1] if len(sys.argv) > 1 else "data.json")\n'
    ),

    # ── argparse CLI ─────────────────────────────────────────────────
    ("argparse_cli", "py"): (
        '"""Sample CLI utility built with argparse."""\n\n'
        'import argparse\n\n\n'
        'def main(argv: list[str] | None = None) -> int:\n'
        '    parser = argparse.ArgumentParser(description="Sample CLI tool.")\n'
        '    parser.add_argument("name", help="who to greet")\n'
        '    parser.add_argument("-n", "--repeat", type=int, default=1, help="times to greet")\n'
        '    parser.add_argument("--shout", action="store_true", help="UPPER-CASE the greeting")\n'
        '    args = parser.parse_args(argv)\n\n'
        '    msg = f"Hello, {args.name}!"\n'
        '    if args.shout:\n'
        '        msg = msg.upper()\n'
        '    for _ in range(args.repeat):\n'
        '        print(msg)\n'
        '    return 0\n\n\n'
        'if __name__ == "__main__":\n'
        '    raise SystemExit(main())\n'
    ),

    # ── Todo list ────────────────────────────────────────────────────
    ("todo_list", "py"): (
        '"""Tiny todo-list app — JSON file as storage."""\n\n'
        'import json\n'
        'import sys\n'
        'from pathlib import Path\n\n'
        'STORE = Path("todos.json")\n\n\n'
        'def load() -> list[dict]:\n'
        '    return json.loads(STORE.read_text(encoding="utf-8")) if STORE.exists() else []\n\n\n'
        'def save(items: list[dict]) -> None:\n'
        '    STORE.write_text(json.dumps(items, indent=2, ensure_ascii=False), encoding="utf-8")\n\n\n'
        'def main(argv: list[str]) -> int:\n'
        '    items = load()\n'
        '    if not argv or argv[0] == "list":\n'
        '        for i, t in enumerate(items, 1):\n'
        '            mark = "x" if t["done"] else " "\n'
        '            print(f"  [{mark}] {i}. {t[\\"text\\"]}")\n'
        '        return 0\n'
        '    cmd = argv[0]\n'
        '    if cmd == "add":\n'
        '        items.append({"text": " ".join(argv[1:]), "done": False})\n'
        '        save(items)\n'
        '    elif cmd == "done":\n'
        '        items[int(argv[1]) - 1]["done"] = True\n'
        '        save(items)\n'
        '    return 0\n\n\n'
        'if __name__ == "__main__":\n'
        '    raise SystemExit(main(sys.argv[1:]))\n'
    ),

    # ── HTML page ────────────────────────────────────────────────────
    ("html_page", "html"): (
        "<!doctype html>\n<html lang='en'>\n<head>\n"
        "  <meta charset='utf-8'>\n"
        "  <title>Generated landing page</title>\n"
        "  <style>\n"
        "    body{margin:0;font-family:system-ui,sans-serif;background:#0e1116;color:#e6edf3;\n"
        "         display:flex;min-height:100vh;align-items:center;justify-content:center;text-align:center;}\n"
        "    .hero{padding:64px 32px;}\n"
        "    h1{font-size:48px;margin-bottom:.5rem;}\n"
        "    p{color:#8b949e;font-size:18px;}\n"
        "    a{display:inline-block;margin-top:1.5rem;padding:.7rem 1.4rem;\n"
        "      background:#58a6ff;color:#0d1117;text-decoration:none;border-radius:8px;font-weight:700;}\n"
        "  </style>\n</head>\n<body>\n"
        "  <main class='hero'>\n"
        "    <h1>Generated by LocalAgent</h1>\n"
        "    <p>Edit this file to make it your own.</p>\n"
        "    <a href='#'>Get started</a>\n"
        "  </main>\n</body>\n</html>\n"
    ),

    # ── HTML form ────────────────────────────────────────────────────
    ("html_form", "html"): (
        "<!doctype html>\n<html lang='en'>\n<head>\n"
        "  <meta charset='utf-8'><title>Contact form</title>\n"
        "  <style>body{font-family:system-ui;max-width:480px;margin:48px auto;}\n"
        "    label{display:block;margin:.4rem 0;font-weight:600;}\n"
        "    input,textarea{width:100%;padding:.5rem;border:1px solid #ccc;border-radius:6px;}\n"
        "    button{margin-top:1rem;padding:.6rem 1.2rem;background:#0a4a8f;color:white;\n"
        "      border:none;border-radius:6px;cursor:pointer;}</style>\n</head>\n<body>\n"
        "  <h1>Contact us</h1>\n"
        "  <form method='post' action='/submit'>\n"
        "    <label>Name<input name='name' required></label>\n"
        "    <label>Email<input type='email' name='email' required></label>\n"
        "    <label>Message<textarea name='message' rows='5' required></textarea></label>\n"
        "    <button type='submit'>Send</button>\n"
        "  </form>\n</body>\n</html>\n"
    ),

    # ── Snake game (text-mode skeleton) ──────────────────────────────
    ("snake_game", "py"): (
        '"""Snake-game core (no curses; just the move + collision logic)."""\n\n'
        'def step(snake: list[tuple[int, int]], direction: str, food: tuple[int, int]) -> tuple[list, bool, bool]:\n'
        '    dx, dy = {"U":(0,-1),"D":(0,1),"L":(-1,0),"R":(1,0)}[direction]\n'
        '    head = (snake[0][0] + dx, snake[0][1] + dy)\n'
        '    ate = head == food\n'
        '    new_snake = [head] + snake[:-1] if not ate else [head] + snake\n'
        '    crashed = head in snake\n'
        '    return new_snake, ate, crashed\n\n\n'
        'if __name__ == "__main__":\n'
        '    snake = [(5,5),(4,5),(3,5)]\n'
        '    print(step(snake, "R", (6,5)))\n'
    ),

    # ── Rock paper scissors ──────────────────────────────────────────
    ("rock_paper", "py"): (
        '"""Rock-paper-scissors game."""\n\n'
        'import random\n\n'
        'CHOICES = ("rock", "paper", "scissors")\n'
        'BEATS = {"rock": "scissors", "paper": "rock", "scissors": "paper"}\n\n\n'
        'def play(player: str) -> str:\n'
        '    bot = random.choice(CHOICES)\n'
        '    if player == bot:\n'
        '        return f"draw — both chose {bot}"\n'
        '    if BEATS[player] == bot:\n'
        '        return f"player wins ({player} beats {bot})"\n'
        '    return f"bot wins ({bot} beats {player})"\n\n\n'
        'if __name__ == "__main__":\n'
        '    print(play("rock"))\n'
    ),

    # ── Stopwatch ────────────────────────────────────────────────────
    ("stopwatch", "py"): (
        '"""Tiny stopwatch — start, lap, stop."""\n\n'
        'import time\n\n\n'
        'class Stopwatch:\n'
        '    def __init__(self) -> None:\n'
        '        self._start: float | None = None\n'
        '        self._laps: list[float] = []\n\n'
        '    def start(self) -> None:\n'
        '        self._start = time.monotonic()\n\n'
        '    def lap(self) -> float:\n'
        '        if self._start is None:\n'
        '            raise RuntimeError("not started")\n'
        '        elapsed = time.monotonic() - self._start\n'
        '        self._laps.append(elapsed)\n'
        '        return elapsed\n\n'
        '    @property\n'
        '    def laps(self) -> list[float]:\n'
        '        return list(self._laps)\n\n\n'
        'if __name__ == "__main__":\n'
        '    sw = Stopwatch(); sw.start()\n'
        '    time.sleep(0.05)\n'
        '    print(f"lap1 = {sw.lap():.3f}s")\n'
    ),

    # ── Factorial ────────────────────────────────────────────────────
    ("factorial", "py"): (
        '"""Factorial — recursive and iterative."""\n\n'
        'def factorial(n: int) -> int:\n'
        '    if n < 0:\n'
        '        raise ValueError("n must be non-negative")\n'
        '    out = 1\n'
        '    for i in range(2, n + 1):\n'
        '        out *= i\n'
        '    return out\n\n\n'
        'if __name__ == "__main__":\n'
        '    for n in range(7):\n'
        '        print(f"{n}! = {factorial(n)}")\n'
    ),

    # ── Palindrome ───────────────────────────────────────────────────
    ("palindrome", "py"): (
        '"""Palindrome detector — case-insensitive, ignores spaces."""\n\n'
        'def is_palindrome(s: str) -> bool:\n'
        '    cleaned = "".join(c.lower() for c in s if c.isalnum())\n'
        '    return cleaned == cleaned[::-1]\n\n\n'
        'if __name__ == "__main__":\n'
        '    for s in ("racecar", "А роза упала на лапу Азора", "hello"):\n'
        '        print(f"{s!r:40s} -> {is_palindrome(s)}")\n'
    ),

    # ── Anagram check ────────────────────────────────────────────────
    ("anagram", "py"): (
        '"""Anagram detector."""\n\n'
        'def is_anagram(a: str, b: str) -> bool:\n'
        '    norm = lambda s: sorted(c.lower() for c in s if c.isalnum())\n'
        '    return norm(a) == norm(b)\n\n\n'
        'if __name__ == "__main__":\n'
        '    print(is_anagram("listen", "silent"))   # True\n'
        '    print(is_anagram("hello",  "world"))    # False\n'
    ),

    # ── Word counter ─────────────────────────────────────────────────
    ("word_counter", "py"): (
        '"""Count words in a text file."""\n\n'
        'import sys\n'
        'from collections import Counter\n\n\n'
        'def count(path: str, top: int = 10) -> None:\n'
        '    with open(path, encoding="utf-8") as f:\n'
        '        words = f.read().lower().split()\n'
        '    for word, n in Counter(words).most_common(top):\n'
        '        print(f"{n:5d}  {word}")\n\n\n'
        'if __name__ == "__main__":\n'
        '    count(sys.argv[1] if len(sys.argv) > 1 else __file__)\n'
    ),

    # ── FizzBuzz ─────────────────────────────────────────────────────
    ("fizzbuzz", "py"): (
        '"""Classic FizzBuzz."""\n\n'
        'def fizzbuzz(n: int) -> list[str]:\n'
        '    out = []\n'
        '    for i in range(1, n + 1):\n'
        '        if   i % 15 == 0: out.append("FizzBuzz")\n'
        '        elif i %  3 == 0: out.append("Fizz")\n'
        '        elif i %  5 == 0: out.append("Buzz")\n'
        '        else:             out.append(str(i))\n'
        '    return out\n\n\n'
        'if __name__ == "__main__":\n'
        '    print("\\n".join(fizzbuzz(20)))\n'
    ),

    # ── Generic ext fallbacks ────────────────────────────────────────
    ("", "py"):   '"""Auto-generated by LocalAgent.\n\nPrompt: {{PROMPT}}\n"""\n\n# TODO: implement\n',
    ("", "txt"):  "Generated by LocalAgent.\nPrompt: {{PROMPT}}\n",
    ("", "md"):   "# Generated by LocalAgent\n\nPrompt: {{PROMPT}}\n\n## TODO\n\n- write content\n",
    ("", "json"): '{}\n',
    ("", "html"): "<!doctype html>\n<html><body><h1>Generated by LocalAgent</h1></body></html>\n",
    ("", "css"):  "/* Generated by LocalAgent */\nbody{font-family:sans-serif;}\n",
    ("", "js"):   "// Generated by LocalAgent\nconsole.log('hello');\n",
}


# ── action verbs detection ────────────────────────────────────────────


_RUN_KEYWORDS  = re.compile(
    r"\b(run|execute|verify|check it works|test it works|"
    r"запусти|проверь работу|выполни)\b",
    re.IGNORECASE,
)
_LIST_KEYWORDS = re.compile(
    r"\b(list (the )?(workspace|directory|files)|"
    r"что в (рабочей )?папке|покажи файлы|show files)\b",
    re.IGNORECASE,
)
_TEST_KEYWORDS = re.compile(
    r"\b(run pytest|run the tests|запусти тесты|pytest)\b",
    re.IGNORECASE,
)


def wants_run(prompt: str) -> bool:
    return bool(_RUN_KEYWORDS.search(prompt))


def wants_list(prompt: str) -> bool:
    return bool(_LIST_KEYWORDS.search(prompt))


def wants_pytest(prompt: str) -> bool:
    return bool(_TEST_KEYWORDS.search(prompt))


# ── filename extraction ──────────────────────────────────────────────


_FILENAME_RE = re.compile(r"(?<![\w/\\])([A-Za-z0-9_-]+\.[A-Za-z0-9]{1,5})(?![\w/\\])")


def extract_filenames(prompt: str) -> list[str]:
    """Return every plausible filename mentioned in ``prompt`` (preserves order, deduped)."""
    seen: set[str] = set()
    out: list[str] = []
    for match in _FILENAME_RE.finditer(prompt):
        name = match.group(1)
        # Skip path-like tokens — sandbox would refuse them anyway.
        if "/" in name or "\\" in name or ".." in name:
            continue
        # Skip extensions that aren't useful for code generation (urls, etc.).
        if name in seen:
            continue
        seen.add(name)
        out.append(name)
    return out


# ── inline content extraction (kept compatible with old local.py) ────


_INLINE_CONTENT_RE = re.compile(
    r"(?:with\s+content|содержит|содержанием|текст(?:ом)?)\s+"
    r"(?P<q>[\"“«'])"
    r"(?P<body>.+?)"
    r"(?P=q)",
    re.IGNORECASE | re.DOTALL,
)


def extract_inline_content(prompt: str) -> str | None:
    m = _INLINE_CONTENT_RE.search(prompt)
    return m.group("body") if m else None
