"""Brain implementations and the factories that build them.

The orchestrator never imports a concrete brain — it asks this package
for one by provider name. Adding an LLM-backed planner later is as
simple as registering a new entry in ``_PLANNERS`` / ``_CRITICS``:

    from app.brains.brain_openai_planner import OpenAIPlannerBrain
    from app.llm import get_llm_client

    def _openai_planner() -> Planner:
        return OpenAIPlannerBrain(llm=get_llm_client("openai"))

    _PLANNERS["openai"] = _openai_planner

Keep provider-specific imports lazy (inside the builder function) so
optional dependencies stay optional.
"""

from __future__ import annotations

import json
from typing import Callable

from app.brains.base import Critic, Planner
from app.brains.brain1_planner import PlannerBrain
from app.brains.brain1_planner_llm import LLMPlannerBrain
from app.brains.brain2_critic import CriticBrain
from app.brains.brain2_critic_llm import LLMCriticBrain
from app.llm.mock import MockLLMClient

__all__ = [
    "Planner",
    "Critic",
    "PlannerBrain",
    "CriticBrain",
    "build_planner",
    "build_critic",
    "registered_planner_providers",
    "registered_critic_providers",
]

# Canned JSON payloads for the "mock" provider. They represent what a
# well-behaved LLM might return and are used for wiring tests / offline
# demos — not to simulate intelligence. The task_id inside is ignored:
# the LLM brains override it with the caller's id after parsing.
_MOCK_PLAN_PAYLOAD: dict = {
    "task_id": "mock",
    "objective": "[MOCK] Complete the requested task.",
    "assumptions": ["Inputs are well-formed.", "Required tools are available."],
    "constraints": [],
    "risks": ["External dependencies may be unavailable."],
    "steps": [
        "Clarify the requirements with the requester.",
        "Outline the solution at a high level and list the sub-tasks.",
        "Implement each sub-task and verify its output independently.",
        "Validate the full output against every success criterion.",
    ],
    "success_criteria": [
        "All requirements are satisfied.",
        "No critical errors remain in the logs.",
        "The output is reproducible from the recorded steps.",
    ],
    "planner_notes": "Generated by MockLLMClient - wiring test fixture.",
}

_MOCK_CRITIQUE_PAYLOAD: dict = {
    "task_id": "mock",
    "overall_score": 92,
    "strengths": [
        "Objective is clearly stated.",
        "Steps are concrete and ordered.",
        "Success criteria are present.",
    ],
    "weaknesses": [],
    "missing_elements": [],
    "contradictions": [],
    "risk_flags": [],
    "improvement_suggestions": [],
    "revised_step_notes": [],
    "final_judgement": "accepted",
}


def _mock_planner() -> Planner:
    """LLMPlannerBrain over a MockLLMClient with a canned valid plan.

    Exists so the full pipeline (including the LLM brain path) can be
    exercised end-to-end without touching the network.
    """
    return LLMPlannerBrain(
        llm=MockLLMClient(default=json.dumps(_MOCK_PLAN_PAYLOAD)),
    )


def _mock_critic() -> Critic:
    """LLMCriticBrain over a MockLLMClient with a canned valid critique."""
    return LLMCriticBrain(
        llm=MockLLMClient(default=json.dumps(_MOCK_CRITIQUE_PAYLOAD)),
    )


def _anthropic_planner() -> Planner:
    """LLMPlannerBrain talking to the real Anthropic Claude API.

    Construction fails fast if ``ANTHROPIC_API_KEY`` is not set, so the
    operator sees a clear error instead of silently falling back.
    """
    from app.llm import get_llm_client
    return LLMPlannerBrain(llm=get_llm_client("anthropic"))


def _anthropic_critic() -> Critic:
    """LLMCriticBrain talking to the real Anthropic Claude API."""
    from app.llm import get_llm_client
    return LLMCriticBrain(llm=get_llm_client("anthropic"))


# Provider name → zero-arg factory. Keep factories small; put any heavy
# work (API client construction, credential loading) inside the factory
# so importing this module stays fast and side-effect-free.
_PLANNERS: dict[str, Callable[[], Planner]] = {
    "deterministic": PlannerBrain,
    "mock":          _mock_planner,
    "anthropic":     _anthropic_planner,
    # TODO: "openai": build from app.brains.brain_openai_planner
    # TODO: "local":  build from app.brains.brain_local_planner
}

_CRITICS: dict[str, Callable[[], Critic]] = {
    "deterministic": CriticBrain,
    "mock":          _mock_critic,
    "anthropic":     _anthropic_critic,
    # TODO: "openai": build from app.brains.brain_openai_critic
    # TODO: "local":  build from app.brains.brain_local_critic
}


def registered_planner_providers() -> list[str]:
    """Return the names of every currently wired planner provider."""
    return sorted(_PLANNERS)


def registered_critic_providers() -> list[str]:
    """Return the names of every currently wired critic provider."""
    return sorted(_CRITICS)


def build_planner(provider: str = "deterministic") -> Planner:
    """Instantiate a planner for the given provider name.

    Raises:
        ValueError: if the provider name is not registered.
    """
    try:
        return _PLANNERS[provider]()
    except KeyError:
        raise ValueError(
            f"unknown planner provider {provider!r}; "
            f"available: {registered_planner_providers()}"
        ) from None


def build_critic(provider: str = "deterministic") -> Critic:
    """Instantiate a critic for the given provider name.

    Raises:
        ValueError: if the provider name is not registered.
    """
    try:
        return _CRITICS[provider]()
    except KeyError:
        raise ValueError(
            f"unknown critic provider {provider!r}; "
            f"available: {registered_critic_providers()}"
        ) from None
