"""Brain implementations and the factories that build them.

The orchestrator never imports a concrete brain — it asks this package
for one by provider name. Adding an LLM-backed planner later is as
simple as registering a new entry in ``_PLANNERS`` / ``_CRITICS`` /
``_EXECUTORS``:

    from app.brains.brain_openai_planner import OpenAIPlannerBrain
    from app.llm import get_llm_client

    def _openai_planner() -> Planner:
        return OpenAIPlannerBrain(llm=get_llm_client("openai"))

    _PLANNERS["openai"] = _openai_planner

Keep provider-specific imports lazy (inside the builder function) so
optional dependencies stay optional.
"""

from __future__ import annotations

import json
from typing import Callable

from app.brains.base import Critic, Executor, Planner
from app.brains.brain1_planner import PlannerBrain
from app.brains.brain1_planner_llm import LLMPlannerBrain
from app.brains.brain2_critic import CriticBrain
from app.brains.brain2_critic_llm import LLMCriticBrain
from app.brains.brain2_critic_safety import SafetyCritic
from app.brains.brain3_executor import ExecutorBrain
from app.brains.brain3_executor_agent import AgentExecutorBrain
from app.brains.brain3_executor_llm import LLMExecutorBrain
from app.llm.mock import MockLLMClient

__all__ = [
    "Planner",
    "Critic",
    "Executor",
    "PlannerBrain",
    "CriticBrain",
    "ExecutorBrain",
    "build_planner",
    "build_critic",
    "build_executor",
    "registered_planner_providers",
    "registered_critic_providers",
    "registered_executor_providers",
]

# Canned JSON payloads for the "mock" provider. They represent what a
# well-behaved LLM might return and are used for wiring tests / offline
# demos — not to simulate intelligence. The task_id inside is ignored:
# the LLM brains override it with the caller's id after parsing.
_MOCK_PLAN_PAYLOAD: dict = {
    "task_id": "mock",
    "objective": "[MOCK] Complete the requested task.",
    "assumptions": ["Inputs are well-formed.", "Required tools are available."],
    "constraints": [],
    "risks": ["External dependencies may be unavailable."],
    "steps": [
        "Clarify the requirements with the requester.",
        "Outline the solution at a high level and list the sub-tasks.",
        "Implement each sub-task and verify its output independently.",
        "Validate the full output against every success criterion.",
    ],
    "success_criteria": [
        "All requirements are satisfied.",
        "No critical errors remain in the logs.",
        "The output is reproducible from the recorded steps.",
    ],
    "planner_notes": "Generated by MockLLMClient - wiring test fixture.",
}

_MOCK_CRITIQUE_PAYLOAD: dict = {
    "task_id": "mock",
    "overall_score": 92,
    "strengths": [
        "Objective is clearly stated.",
        "Steps are concrete and ordered.",
        "Success criteria are present.",
    ],
    "weaknesses": [],
    "missing_elements": [],
    "contradictions": [],
    "risk_flags": [],
    "improvement_suggestions": [],
    "revised_step_notes": [],
    "final_judgement": "accepted",
}

_MOCK_EXECUTION_PAYLOAD: dict = {
    "task_id": "mock",
    "overall_status": "completed",
    "step_results": [
        {
            "index": 1,
            "step": "Clarify the requirements with the requester.",
            "status": "skipped",
            "output": "Skipped — requires a human stakeholder.",
            "error": "",
        },
        {
            "index": 2,
            "step": "Outline the solution at a high level and list the sub-tasks.",
            "status": "succeeded",
            "output": "Produced a high-level outline with 4 sub-tasks.",
            "error": "",
        },
        {
            "index": 3,
            "step": "Implement each sub-task and verify its output independently.",
            "status": "succeeded",
            "output": "Implemented and individually verified each sub-task.",
            "error": "",
        },
        {
            "index": 4,
            "step": "Validate the full output against every success criterion.",
            "status": "succeeded",
            "output": "All success criteria pass.",
            "error": "",
        },
    ],
    "summary": "completed: 3 succeeded, 1 skipped, 0 failed out of 4 step(s).",
    "executor_notes": "Generated by MockLLMClient - wiring test fixture.",
}


def _mock_planner() -> Planner:
    """LLMPlannerBrain over a MockLLMClient with a canned valid plan.

    Exists so the full pipeline (including the LLM brain path) can be
    exercised end-to-end without touching the network.
    """
    return LLMPlannerBrain(
        llm=MockLLMClient(default=json.dumps(_MOCK_PLAN_PAYLOAD)),
    )


def _mock_critic() -> Critic:
    """LLMCriticBrain over a MockLLMClient with a canned valid critique."""
    return LLMCriticBrain(
        llm=MockLLMClient(default=json.dumps(_MOCK_CRITIQUE_PAYLOAD)),
    )


def _mock_executor() -> Executor:
    """LLMExecutorBrain over a MockLLMClient with a canned valid execution."""
    return LLMExecutorBrain(
        llm=MockLLMClient(default=json.dumps(_MOCK_EXECUTION_PAYLOAD)),
    )


def _anthropic_planner() -> Planner:
    from app.llm import get_llm_client
    return LLMPlannerBrain(llm=get_llm_client("anthropic"))


def _anthropic_critic() -> Critic:
    from app.llm import get_llm_client
    return LLMCriticBrain(llm=get_llm_client("anthropic"))


def _openai_planner() -> Planner:
    from app.llm import get_llm_client
    return LLMPlannerBrain(llm=get_llm_client("openai"))


def _openai_critic() -> Critic:
    from app.llm import get_llm_client
    return LLMCriticBrain(llm=get_llm_client("openai"))


def _openai_executor() -> Executor:
    from app.llm import get_llm_client
    return LLMExecutorBrain(llm=get_llm_client("openai"))


def _openai_agent_executor() -> Executor:
    """Autonomous agent with OpenAI function calling + sandbox."""
    from app import config
    from app.agent.client import AgentClientError, OpenAIAgentClient
    from app.sandbox.fs import Sandbox

    api_key = config.settings.openai_api_key
    if not api_key:
        raise AgentClientError(
            "OPENAI_API_KEY is not set - export it or put it in your .env file"
        )
    return AgentExecutorBrain(
        client=OpenAIAgentClient(api_key=api_key, model=config.settings.openai_model),
        sandbox=Sandbox(config.settings.agent_workspace),
    )


def _anthropic_executor() -> Executor:
    """LLMExecutorBrain talking to the real Anthropic Claude API."""
    from app.llm import get_llm_client
    return LLMExecutorBrain(llm=get_llm_client("anthropic"))


def _agent_executor() -> Executor:
    """Autonomous agent executor — Claude with sandboxed file tools.

    Construction fails fast if ``ANTHROPIC_API_KEY`` is not set so the
    operator gets a clear error instead of a silent fallback. The agent
    is confined to ``settings.agent_workspace``; absolute paths and
    traversal segments are rejected by the sandbox before any I/O.
    """
    from app import config
    from app.agent.client import AgentClientError, AnthropicAgentClient
    from app.sandbox.fs import Sandbox

    api_key = config.settings.anthropic_api_key
    if not api_key:
        raise AgentClientError(
            "ANTHROPIC_API_KEY is not set - export it or put it in your .env file"
        )
    return AgentExecutorBrain(
        client=AnthropicAgentClient(api_key=api_key, model=config.settings.agent_model),
        sandbox=Sandbox(config.settings.agent_workspace),
    )


def _local_agent_executor() -> Executor:
    """Offline autonomous executor — pattern-matches the prompt, writes real files.

    No API key required. Useful for offline demos and to verify the agent
    loop is wired correctly without spending Anthropic credits. The
    ``LocalAgentClient`` extracts a target filename + best-effort content
    from the prompt and produces a real ``write_file`` tool call against
    the same sandbox the network agent uses.
    """
    from app import config
    from app.agent.local import LocalAgentClient
    from app.sandbox.fs import Sandbox

    return AgentExecutorBrain(
        client=LocalAgentClient(),
        sandbox=Sandbox(config.settings.agent_workspace),
    )


# Provider name → zero-arg factory. Keep factories small; put any heavy
# work (API client construction, credential loading) inside the factory
# so importing this module stays fast and side-effect-free.
_PLANNERS: dict[str, Callable[[], Planner]] = {
    "deterministic": PlannerBrain,
    "mock":          _mock_planner,
    "anthropic":     _anthropic_planner,
    "openai":        _openai_planner,
}

_CRITICS: dict[str, Callable[[], Critic]] = {
    "deterministic": CriticBrain,
    "mock":          _mock_critic,
    "anthropic":     _anthropic_critic,
    "openai":        _openai_critic,
    "safety":        SafetyCritic,
}

_EXECUTORS: dict[str, Callable[[], Executor]] = {
    "deterministic": ExecutorBrain,
    "mock":          _mock_executor,
    "anthropic":     _anthropic_executor,
    "agent":         _agent_executor,
    "local-agent":   _local_agent_executor,
    "openai":        _openai_executor,
    "openai-agent":  _openai_agent_executor,
}


def registered_planner_providers() -> list[str]:
    """Return the names of every currently wired planner provider."""
    return sorted(_PLANNERS)


def registered_critic_providers() -> list[str]:
    """Return the names of every currently wired critic provider."""
    return sorted(_CRITICS)


def registered_executor_providers() -> list[str]:
    """Return the names of every currently wired executor provider."""
    return sorted(_EXECUTORS)


def build_planner(provider: str = "deterministic") -> Planner:
    """Instantiate a planner for the given provider name.

    Raises:
        ValueError: if the provider name is not registered.
    """
    try:
        return _PLANNERS[provider]()
    except KeyError:
        raise ValueError(
            f"unknown planner provider {provider!r}; "
            f"available: {registered_planner_providers()}"
        ) from None


def build_critic(provider: str = "deterministic") -> Critic:
    """Instantiate a critic for the given provider name.

    Raises:
        ValueError: if the provider name is not registered.
    """
    try:
        return _CRITICS[provider]()
    except KeyError:
        raise ValueError(
            f"unknown critic provider {provider!r}; "
            f"available: {registered_critic_providers()}"
        ) from None


def build_executor(provider: str = "deterministic") -> Executor:
    """Instantiate an executor for the given provider name.

    Raises:
        ValueError: if the provider name is not registered.
    """
    try:
        return _EXECUTORS[provider]()
    except KeyError:
        raise ValueError(
            f"unknown executor provider {provider!r}; "
            f"available: {registered_executor_providers()}"
        ) from None


# Provider names that touch the filesystem. They must be re-built per
# user so each user gets an isolated workspace/<username>/ directory.
_FILESYSTEM_PROVIDERS: frozenset[str] = frozenset(
    {"agent", "local-agent", "openai-agent"}
)


def build_per_user_executor(provider: str, username: str | None) -> Executor:
    """Build an executor with a per-user sandbox when the provider needs one.

    For ``agent`` / ``local-agent`` / ``openai-agent`` providers, the
    sandbox root becomes ``<agent_workspace>/<username>``. For every
    other provider (deterministic, mock, anthropic, openai) the call
    reduces to a plain ``build_executor(provider)`` because those paths
    never touch the disk.

    When ``username`` is ``None`` (auth disabled) the shared default
    workspace is used — same as the single-user mode.
    """
    if provider not in _FILESYSTEM_PROVIDERS or not username:
        return build_executor(provider)

    from app import config
    from app.brains.brain3_executor_agent import AgentExecutorBrain
    from app.sandbox import Sandbox, user_workspace

    user_ws = user_workspace(config.settings.agent_workspace, username)
    sandbox = Sandbox(user_ws)

    if provider == "local-agent":
        from app.agent.local import LocalAgentClient
        return AgentExecutorBrain(client=LocalAgentClient(), sandbox=sandbox)

    if provider == "agent":
        from app.agent.client import AgentClientError, AnthropicAgentClient
        api_key = config.settings.anthropic_api_key
        if not api_key:
            raise AgentClientError("ANTHROPIC_API_KEY is not set")
        return AgentExecutorBrain(
            client=AnthropicAgentClient(api_key=api_key, model=config.settings.agent_model),
            sandbox=sandbox,
        )

    if provider == "openai-agent":
        from app.agent.client import AgentClientError, OpenAIAgentClient
        api_key = config.settings.openai_api_key
        if not api_key:
            raise AgentClientError("OPENAI_API_KEY is not set")
        return AgentExecutorBrain(
            client=OpenAIAgentClient(api_key=api_key, model=config.settings.openai_model),
            sandbox=sandbox,
        )

    # Unreachable — kept for the type checker.
    return build_executor(provider)
